#!/usr/bin/env python3
"""
Email Marketing Skill — Automated Setup
This script prepares the email marketing skill for immediate use once SMTP credentials are provided.

It will:
1. Prompt for SMTP credentials (or read from env vars)
2. Create a reusable `send_campaign.py` with your settings baked in
3. Generate a sample `recipients.csv` template
4. Create a test script to validate the connection
5. Output a cron template for scheduled sends

Run this whenever you have credentials ready. It's safe to run multiple times.
"""

import os
import sys
import json
from pathlib import Path

BASE_DIR = Path(__file__).parent.resolve()
SKILL_DIR = BASE_DIR / "skills" / "email-marketing"
if not SKILL_DIR.exists():
    print(f"ERROR: Skill directory not found: {SKILL_DIR}")
    sys.exit(1)

def prompt_or_env(var_name, prompt):
    """Get value from environment if set, else prompt user."""
    val = os.environ.get(var_name)
    if val:
        print(f"{var_name} found in environment.")
        return val
    return input(prompt).strip()

def main():
    print("=== Email Marketing Skill Setup ===\n")
    
    # 1. Gather SMTP credentials
    print("Step 1: Enter SMTP credentials")
    print("(Press Enter to skip if you want to fill manually later)\n")
    
    smtp_host = prompt_or_env("SMTP_HOST", "SMTP host (e.g., smtp.gmail.com: ") or "smtp.gmail.com"
    smtp_port = prompt_or_env("SMTP_PORT", "SMTP port [587]: ") or "587"
    username = prompt_or_env("SMTP_USERNAME", "SMTP username (your email): ")
    password = prompt_or_env("SMTP_PASSWORD", "SMTP password/app password: ")
    from_email = prompt_or_env("FROM_EMAIL", "From email address: ") or username
    from_name = prompt_or_env("FROM_NAME", "From name [Agent Gunna]: ") or "Agent Gunna"
    use_tls = prompt_or_env("SMTP_USE_TLS", "Use TLS? [y/N]: ").lower() in ('y', 'yes', '1')
    
    if not all([username, password]):
        print("\nWARNING: Username and password required for setup. Skipping bake-in.")
        print("You can configure manually using CONFIG.md or re-run this script later.")
        return
    
    # 2. Create send_campaign.py (baked config)
    campaign_script = BASE_DIR / "send_campaign.py"
    campaign_content = f'''#!/usr/bin/env python3
"""
Pre-configured email campaign sender.
Generated by setup_email_marketing.py on {os.popen('date').read().strip()}
"""

import os
import sys
from pathlib import Path

# Add skill to path
SKILL_DIR = Path(__file__).parent / "skills" / "email-marketing"
sys.path.insert(0, str(SKILL_DIR))

from email_marketing import send_batch_email

# --- YOUR CONFIGURATION (baked in) ---
SMTP_CONFIG = {{
    "smtp_host": "{smtp_host}",
    "smtp_port": {smtp_port},
    "username": "{username}",
    "password": "{password}",
    "from_email": "{from_email}",
    "from_name": "{from_name}",
    "use_tls": {use_tls},
    "batch_size": 25
}}

# Load recipients from CSV (default: recipients.csv)
def load_recipients(csv_path):
    import csv
    recipients = []
    with open(csv_path, newline='', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            recipients.append({{"email": row["email"].strip(), "name": row.get("name", "").strip()}})
    return recipients

def main():
    if len(sys.argv) < 2:
        print("Usage: python send_campaign.py <recipients.csv> <subject> <body_template_file>")
        print("Example: python send_campaign.py recipients.csv 'Check this out' body.txt")
        sys.exit(1)
    
    csv_path = sys.argv[1]
    subject = sys.argv[2]
    template_file = sys.argv[3] if len(sys.argv) > 3 else None
    
    if template_file:
        with open(template_file, encoding='utf-8') as f:
            body_template = f.read()
    else:
        body_template = input("Enter body template (use {{name}} for personalization):\\n")
    
    recipients = load_recipients(csv_path)
    print(f"Loaded {{len(recipients)}} recipients from {{csv_path}}")
    
    result = send_batch_email(
        **SMTP_CONFIG,
        subject=subject,
        body_template=body_template,
        recipients=recipients
    )
    
    print(json.dumps(result, indent=2))

if __name__ == "__main__":
    main()
'''
    campaign_script.write_text(campaign_content)
    print(f"✓ Created {campaign_script.relative_to(BASE_DIR)}")
    
    # 3. Create sample recipients.csv
    sample_csv = BASE_DIR / "recipients_sample.csv"
    sample_csv.write_text("email,name\n")
    print(f"✓ Created {sample_csv.relative_to(BASE_DIR)}")
    
    # 4. Create test script
    test_script = BASE_DIR / "test_email.py"
    test_content = f'''#!/usr/bin/env python3
"""
Test email delivery to yourself.
"""

import sys
from pathlib import Path

BASE_DIR = Path(__file__).parent.resolve()
sys.path.insert(0, str(BASE_DIR / "skills" / "email-marketing"))

from email_marketing import send_batch_email

# Use the same config as send_campaign.py
SMTP_CONFIG = {{
    "smtp_host": "{smtp_host}",
    "smtp_port": {smtp_port},
    "username": "{username}",
    "password": "{password}",
    "from_email": "{from_email}",
    "from_name": "{from_name}",
    "use_tls": {use_tls},
    "batch_size": 1
}}

def main():
    # Send a single test email to yourself
    result = send_batch_email(
        **SMTP_CONFIG,
        subject="[TEST] Email Marketing Skill Working",
        body_template="Hi {{name}},\\n\\nIf you see this, email sending is working from Agent Gunna.",
        recipients=[{{"email": "{from_email}", "name": "Me"}}]
    )
    print(json.dumps(result, indent=2))

if __name__ == "__main__":
    main()
'''
    test_script.write_text(test_content)
    test_script.chmod(0o755)
    print(f"✓ Created {test_script.relative_to(BASE_DIR)} (executable)")
    
    # 5. Create cron template
    cron_template = BASE_DIR / "cron_email_example.txt"
    cron_content = f'''# Example crontab entry to send weekly newsletter
# Run every Monday at 9 AM
0 9 * * 1 cd {BASE_DIR} && python3 send_campaign.py recipients.csv "Weekly Update" body.txt >> memory/email_log.txt 2>&1
'''
    cron_template.write_text(cron_content)
    print(f"✓ Created {cron_template.relative_to(BASE_DIR)}")
    
    # 6. Print next steps
    print("\n--- Setup Complete ---")
    print("Next steps:")
    print(f"1. Test the connection: python3 {test_script.relative_to(BASE_DIR)}")
    print("2. Edit recipients_sample.csv → recipients.csv with your list")
    print("3. Create body.txt with your email content (use {name})")
    print(f"4. Send a campaign: python3 {campaign_script.relative_to(BASE_DIR)} recipients.csv \"Your Subject\" body.txt")
    print(f"5. Add to crontab using template: crontab -e (see {cron_template.relative_to(BASE_DIR)})")
    print("\nNote: Credentials are baked into send_campaign.py and test_email.py. Keep these files secure and gitignored.")

if __name__ == "__main__":
    main()
